export const CREATE_BLOG_REQUEST = "CREATE_BLOG_REQUEST"
export const CREATE_BLOG_SUCCESS = "CREATE_BLOG_SUCCESS"
export const CREATE_BLOG_FAILURE = "CREATE_BLOG_FAILURE"

export const GET_BLOGS_REQUEST = "GET_BLOGS_REQUEST"
export const GET_BLOGS_SUCCESS = "GET_BLOGS_SUCCESS"
export const GET_BLOGS_FAILURE = "GET_BLOGS_FAILURE"

export const GET_USER_BLOGS_REQUEST = "GET_USER_BLOGS_REQUEST"
export const GET_USER_BLOGS_SUCCESS = "GET_USER_BLOGS_SUCCESS"
export const GET_USER_BLOGS_FAILURE = "GET_USER_BLOGS_FAILURE"

export const GET_BLOG_REQUEST = "GET_BLOG_REQUEST"
export const GET_BLOG_SUCCESS = "GET_BLOG_SUCCESS"
export const GET_BLOG_FAILURE = "GET_BLOG_FAILURE"

export const UPDATE_BLOG_REQUEST = "UPDATE_BLOG_REQUEST"
export const UPDATE_BLOG_SUCCESS = "UPDATE_BLOG_SUCCESS"
export const UPDATE_BLOG_FAILURE = "UPDATE_BLOG_FAILURE"

export const DELETE_BLOG_REQUEST = "DELETE_BLOG_REQUEST"
export const DELETE_BLOG_SUCCESS = "DELETE_BLOG_SUCCESS"
export const DELETE_BLOG_FAILURE = "DELETE_BLOG_FAILURE"
